#
# ~/.zprofile
#

[[ -f ~/.zshrc ]] && . ~/.zshrc

# start Xorg on login
if [[ ! $DISPLAY && $XDG_VTNR -eq 1 ]]; then
  #exec startx
  #exec WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card2 sway --debug &> sway.log
  #exec env WLR_RENDERER_ALLOW_SOFTWARE=1 env WLR_DRM_DEVICES=/dev/dri/card0:/dev/dri/card2 sway --debug &> sway_normal.log
  exec sway
fi
