#!/usr/bin/zsh

#
# ~/.zshrc
#

export TERM="xterm-color"

# termite shell from current dir
#if [[ $TERM == xterm-color ]]; then
#  . /etc/profile.d/vte.sh
#  __vte_osc7
#fi

# Check if zplug is installed
if [[ ! -d $HOME/.zplug ]];
then
	git clone https://github.com/zplug/zplug ~/.zplug
	source $HOME/.zplug/init.zsh && zplug update --self
fi

# Init zplug
source $HOME/.zplug/init.zsh

# Plugins
zplug "zsh-users/zsh-syntax-highlighting"
zplug "robbyrussell/oh-my-zsh", from:github, use:"lib/*.zsh"
zplug "plugins/command-not-found", from:oh-my-zsh
zplug "plugins/vi-mode", from:oh-my-zsh
zplug "plugins/colorize", from:oh-my-zsh
zplug "plugins/history-substring-search", from:oh-my-zsh

# Theme
zplug "themes/refined", from:oh-my-zsh, as:plugin

# Load plugins that have not been installed yet
if ! zplug check --verbose;
then
	printf "Install? [y/N]: "
	if read -q; then
        echo; zplug install
    else
        echo
    fi
fi

zplug load

# Vi mode
bindkey -v

# History settings
HISTFILE="$HOME/.zsh_history"
HISTSIZE=10000
SAVEHIST=1000

autoload -Uz up-line-or-beginning-search down-line-or-beginning-search
zle -N up-line-or-beginning-search
zle -N down-line-or-beginning-search

[[ -n "$key[Up]"   ]] && bindkey -- "$key[Up]"   up-line-or-beginning-search
[[ -n "$key[Down]" ]] && bindkey -- "$key[Down]" down-line-or-beginning-search

# Alt dot
bindkey "^[." insert-last-word

# Source aliases and functions
if [[ -f $HOME/.zsh_aliases ]];
then
	source $HOME/.zsh_aliases
fi
if [[ -f $HOME/.zsh_functions ]];
then
	source $HOME/.zsh_functions
fi

# Source base16 color
source $HOME/.config/base16-shell/base16-current.sh

neofetch --cpu_temp on --gtk2 off --gtk3 off --refresh_rate on

# Cursor style
echo -ne "\e[6 q"

zle-keymap-select () {
	if [ "$TERM" = "xterm-color" ]; then
		if [ $KEYMAP = vicmd ]; then
		    # the command mode for vi
		    echo -ne "\e[2 q"
		else
		    # the insert mode for vi
		    echo -ne "\e[6 q"
		fi
	fi
}

# Set grim directory
export GRIM_DEFAULT_DIR=$HOME/Documents/Screenshots

# Add to path
PATH="$PATH:$HOME/.local/bin"

if type rg &> /dev/null; then
  export FZF_DEFAULT_COMMAND='rg --files'
  export FZF_DEFAULT_OPTS='-m --height 50% --border'
fi

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
